#!/usr/bin/env php
<?php
if(!chdir(realpath(dirname(__FILE__)))){
	fwrite(STDERR, "Couldn't load files on ".realpath(dirname(__FILE__)));
	die(1);
}

// Set time zone and error reporting.
date_default_timezone_set("GMT");
error_reporting(E_ALL ^ E_STRICT);

require_once 'functions.php';
require_once 'AigisBot.php';

if(!isset($argv[1])){
	fwrite(STDERR, "Usage: {$argv[0]} <network>\n");
	die(1);
}
$network = $argv[1];

try{
	// Start Aigis.
	$AigisBot = new AigisBot($network);

	// Load modules.
	$ConnIRC = $AigisBot->loadModule('ConnIRC');
	$PlugIRC = $AigisBot->loadModule('PlugIRC');
	$UserIRC = $AigisBot->loadModule('UserIRC');
	$MIM     = $AigisBot->loadModule('MessIRCManager');

	// Set error handler.
	set_error_handler(array($AigisBot, 'errorHandler'));
}catch(Exception $e){
	fwrite(STDERR, $e->getMessage()."\n");
	exit(2);
}
// IRC loop.
$lastMsg = $lastConn = $lastPing = 0;
while(true){
	if(!$ConnIRC->connected())
		$ConnIRC->connect();

	// Parse IRC messages.
	if($data = $ConnIRC->read()){
		$lastMsg = time();
		$MessIRC = $MIM->getMessage($data);
		$AigisBot->verboseSend($data, 'IRC');

		$AigisBot->sendToModules('ircMessage', $MessIRC);
	}

	// Ping timeouts.
	$time = time();
	if($time - $lastMsg >= ConnIRC::ACTIVITY_TIMEOUT &&
	$time - $lastConn >= ConnIRC::RECONNECT_DELAY){
		$AigisBot->consoleSend('Disconnected for ping timeout.', 'IRC', '!');
	}

	// Send pings after a small amount of time.
	if($time - $lastPing >= ConnIRC::PING_FREQUENCY)
		$ConnIRC->send("PING :AigisBot");
}
